package org.tzi.use.smt.solver;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** An SMT-LIB script under construction: a logic, declarations, and assertions. */
public final class SmtScript {

  private final String logic;
  private final Map<String, SmtSort> declarations = new LinkedHashMap<>();
  private final List<SmtTerm> assertions = new ArrayList<>();

  public SmtScript(String logic) {
    this.logic = logic;
  }

  /**
   * Declares one SMT-LIB constant, refusing a name that is already taken.
   *
   * <p>The refusal is deliberately loud (fail-closed): nothing here aliases the second declaration
   * onto the first, so no assertion is ever silently retargeted at a symbol of the wrong sort and
   * no malformed script reaches the solver.
   *
   * <p>The message names the LIKELY CAUSE rather than only the clashing symbol, because the symbol
   * is one this encoder minted -- {@code <Class>_<i>}, {@code <Class>_<i>_<attr>}, {@code
   * <Class>_<i>_<attr>_value}, {@code <Association>_<i>} -- and appears nowhere in the model the
   * user wrote. Every builder mints into this one flat namespace with no reserved-name discipline,
   * so a model whose own class, attribute, role or association identifier happens to spell one of
   * those shapes collides and is refused even though the model is perfectly legal USE (see
   * {@code SymbolNamespaceCollisionTest} for three reproductions, and the feature matrix's
   * {@code smt.symbol-namespace-collisions} row for why this is a documented limitation rather
   * than a repaired one). Without the added sentence the message gives a reader no route at all
   * from the internal symbol back to the model identifier that caused it.
   */
  public void declareConst(String name, SmtSort sort) {
    SmtSort previous = declarations.putIfAbsent(name, sort);
    if (previous != null) {
      throw new IllegalArgumentException(
          "internal SMT symbol '"
              + name
              + "' is already declared with sort "
              + previous.smtName()
              + " and cannot be redeclared as "
              + sort.smtName()
              + ". This symbol is generated by the encoder, not written in your model: the likely"
              + " cause is a model identifier (a class, attribute, role or association name) that"
              + " spells one of the encoder's internal symbol shapes -- <Class>_<index>,"
              + " <Class>_<index>_<attribute>, <Class>_<index>_<attribute>_value/_uncertainty, or"
              + " <Association>_<index>. Renaming that model element resolves the collision.");
    }
  }

  public void assertThat(SmtTerm term) {
    assertions.add(term);
  }

  public Set<String> declaredNames() {
    return declarations.keySet();
  }

  public String toSmtLib() {
    StringBuilder out = new StringBuilder();
    out.append("(set-logic ").append(logic).append(")\n");
    for (Map.Entry<String, SmtSort> declaration : declarations.entrySet()) {
      out.append("(declare-const ")
          .append(declaration.getKey())
          .append(' ')
          .append(declaration.getValue().smtName())
          .append(")\n");
    }
    for (SmtTerm assertion : assertions) {
      out.append("(assert ").append(assertion.toSmtLib()).append(")\n");
    }
    out.append("(check-sat)\n");
    out.append("(get-model)");
    return out.toString();
  }
}
