[main]
Widget_min = 2
Widget_max = 2
Widget_wname = Set{'alpha', 'beta'}

Gadget_min = 2
Gadget_max = 2
Gadget_targetname = Set{'alpha', 'beta'}

Gadget_WidgetNameMatches = active
Gadget_NoMatchIsUndefined = inactive

[mismatched]
Widget_min = 2
Widget_max = 2
Widget_wname = Set{'alpha', 'beta'}

Gadget_min = 2
Gadget_max = 2
Gadget_targetname = Set{'gamma', 'delta'}

Gadget_WidgetNameMatches = active
Gadget_NoMatchIsUndefined = inactive
